using System;

namespace Magnesium.Vulkan
{
	internal enum VkStructureType : uint
	{
		StructureTypeApplicationInfo = 0,
		StructureTypeInstanceCreateInfo = 1,
		StructureTypeDeviceQueueCreateInfo = 2,
		StructureTypeDeviceCreateInfo = 3,
		StructureTypeSubmitInfo = 4,
		StructureTypeMemoryAllocateInfo = 5,
		StructureTypeMappedMemoryRange = 6,
		StructureTypeBindSparseInfo = 7,
		StructureTypeFenceCreateInfo = 8,
		StructureTypeSemaphoreCreateInfo = 9,
		StructureTypeEventCreateInfo = 10,
		StructureTypeQueryPoolCreateInfo = 11,
		StructureTypeBufferCreateInfo = 12,
		StructureTypeBufferViewCreateInfo = 13,
		StructureTypeImageCreateInfo = 14,
		StructureTypeImageViewCreateInfo = 15,
		StructureTypeShaderModuleCreateInfo = 16,
		StructureTypePipelineCacheCreateInfo = 17,
		StructureTypePipelineShaderStageCreateInfo = 18,
		StructureTypePipelineVertexInputStateCreateInfo = 19,
		StructureTypePipelineInputAssemblyStateCreateInfo = 20,
		StructureTypePipelineTessellationStateCreateInfo = 21,
		StructureTypePipelineViewportStateCreateInfo = 22,
		StructureTypePipelineRasterizationStateCreateInfo = 23,
		StructureTypePipelineMultisampleStateCreateInfo = 24,
		StructureTypePipelineDepthStencilStateCreateInfo = 25,
		StructureTypePipelineColorBlendStateCreateInfo = 26,
		StructureTypePipelineDynamicStateCreateInfo = 27,
		StructureTypeGraphicsPipelineCreateInfo = 28,
		StructureTypeComputePipelineCreateInfo = 29,
		StructureTypePipelineLayoutCreateInfo = 30,
		StructureTypeSamplerCreateInfo = 31,
		StructureTypeDescriptorSetLayoutCreateInfo = 32,
		StructureTypeDescriptorPoolCreateInfo = 33,
		StructureTypeDescriptorSetAllocateInfo = 34,
		StructureTypeWriteDescriptorSet = 35,
		StructureTypeCopyDescriptorSet = 36,
		StructureTypeFramebufferCreateInfo = 37,
		StructureTypeRenderPassCreateInfo = 38,
		StructureTypeCommandPoolCreateInfo = 39,
		StructureTypeCommandBufferAllocateInfo = 40,
		StructureTypeCommandBufferInheritanceInfo = 41,
		StructureTypeCommandBufferBeginInfo = 42,
		StructureTypeRenderPassBeginInfo = 43,
		StructureTypeBufferMemoryBarrier = 44,
		StructureTypeImageMemoryBarrier = 45,
		StructureTypeMemoryBarrier = 46,
		StructureTypeLoaderInstanceCreateInfo = 47,
		StructureTypeLoaderDeviceCreateInfo = 48,
		StructureTypeSwapchainCreateInfoKhr = 1000001000,
		StructureTypePresentInfoKhr = 1000001001,
		StructureTypeDisplayModeCreateInfoKhr = 1000002000,
		StructureTypeDisplaySurfaceCreateInfoKhr = 1000002001,
		StructureTypeDisplayPresentInfoKhr = 1000003000,
		StructureTypeXlibSurfaceCreateInfoKhr = 1000004000,
		StructureTypeXcbSurfaceCreateInfoKhr = 1000005000,
		StructureTypeWaylandSurfaceCreateInfoKhr = 1000006000,
		StructureTypeMirSurfaceCreateInfoKhr = 1000007000,
		StructureTypeAndroidSurfaceCreateInfoKhr = 1000008000,
		StructureTypeWin32SurfaceCreateInfoKhr = 1000009000,
		StructureTypeDebugReportCallbackCreateInfoExt = 1000011000,
		StructureTypePipelineRasterizationStateRasterizationOrderAmd = 1000018000,
		StructureTypeDebugMarkerObjectNameInfoExt = 1000022000,
		StructureTypeDebugMarkerObjectTagInfoExt = 1000022001,
		StructureTypeDebugMarkerMarkerInfoExt = 1000022002,
		StructureTypeDedicatedAllocationImageCreateInfoNv = 1000026000,
		StructureTypeDedicatedAllocationBufferCreateInfoNv = 1000026001,
		StructureTypeDedicatedAllocationMemoryAllocateInfoNv = 1000026002,
	}
}
