namespace Magnesium
{
    public enum MgDebugReportObjectTypeEXT : byte
	{
		UNKNOWN_EXT = 0,
		INSTANCE_EXT = 1,
		PHYSICAL_DEVICE_EXT = 2,
		DEVICE_EXT = 3,
		QUEUE_EXT = 4,
		SEMAPHORE_EXT = 5,
		COMMAND_BUFFER_EXT = 6,
		FENCE_EXT = 7,
		DEVICE_MEMORY_EXT = 8,
		BUFFER_EXT = 9,
		IMAGE_EXT = 10,
		EVENT_EXT = 11,
		QUERY_POOL_EXT = 12,
		BUFFER_VIEW_EXT = 13,
		IMAGE_VIEW_EXT = 14,
		SHADER_MODULE_EXT = 15,
		PIPELINE_CACHE_EXT = 16,
		PIPELINE_LAYOUT_EXT = 17,
		RENDER_PASS_EXT = 18,
		PIPELINE_EXT = 19,
		DESCRIPTOR_SET_LAYOUT_EXT = 20,
		SAMPLER_EXT = 21,
		DESCRIPTOR_POOL_EXT = 22,
		DESCRIPTOR_SET_EXT = 23,
		FRAMEBUFFER_EXT = 24,
		COMMAND_POOL_EXT = 25,
		SURFACE_KHR_EXT = 26,
		SWAPCHAIN_KHR_EXT = 27,
		DEBUG_REPORT_EXT = 28,
	}
}

