using System;

namespace Magnesium
{
    // Device
    public interface IMgDevice
	{
		PFN_vkVoidFunction GetDeviceProcAddr(string pName);
		void DestroyDevice(IMgAllocationCallbacks allocator);
		void GetDeviceQueue(UInt32 queueFamilyIndex, UInt32 queueIndex, out IMgQueue pQueue);
		MgResult DeviceWaitIdle();
		MgResult AllocateMemory(MgMemoryAllocateInfo pAllocateInfo, IMgAllocationCallbacks allocator, out IMgDeviceMemory pMemory);
		//void FreeMemory(MgDeviceMemory memory, MgAllocationCallbacks allocator);
		//MgResult MapMemory(MgDeviceMemory memory, UInt64 offset, UInt64 size, UInt32 flags, out IntPtr ppData);
		//void UnmapMemory(MgDeviceMemory memory);
		MgResult FlushMappedMemoryRanges(MgMappedMemoryRange[] pMemoryRanges);
		MgResult InvalidateMappedMemoryRanges(MgMappedMemoryRange[] pMemoryRanges);
		void GetDeviceMemoryCommitment(IMgDeviceMemory memory, ref UInt64 pCommittedMemoryInBytes);
		void GetBufferMemoryRequirements(IMgBuffer buffer, out MgMemoryRequirements pMemoryRequirements);
		//MgResult BindBufferMemory(IMgBuffer buffer, IMgDeviceMemory memory, UInt64 memoryOffset);
		void GetImageMemoryRequirements(IMgImage image, out MgMemoryRequirements memoryRequirements);
		//MgResult BindImageMemory(IMgImage image, IMgDeviceMemory memory, UInt64 memoryOffset);
		void GetImageSparseMemoryRequirements(IMgImage image, out MgSparseImageMemoryRequirements[] sparseMemoryRequirements);
		MgResult CreateFence(MgFenceCreateInfo pCreateInfo, IMgAllocationCallbacks allocator, out IMgFence fence);
		//void DestroyFence(IMgFence fence, MgAllocationCallbacks allocator);
		MgResult ResetFences(IMgFence[] pFences);
		MgResult GetFenceStatus(IMgFence fence);
		MgResult WaitForFences(IMgFence[] pFences, bool waitAll, UInt64 timeout);
		MgResult CreateSemaphore(MgSemaphoreCreateInfo pCreateInfo, IMgAllocationCallbacks allocator, out IMgSemaphore pSemaphore);
		//void DestroySemaphore(MgSemaphore semaphore, MgAllocationCallbacks allocator);
		MgResult CreateEvent(MgEventCreateInfo pCreateInfo, IMgAllocationCallbacks allocator, out IMgEvent @event);
		//void DestroyEvent(MgEvent @event, MgAllocationCallbacks allocator);
//		MgResult GetEventStatus(IMgEvent @event);
//		MgResult SetEvent(IMgEvent @event);
//		MgResult ResetEvent(IMgEvent @event);
		MgResult CreateQueryPool(MgQueryPoolCreateInfo pCreateInfo, IMgAllocationCallbacks allocator, out IMgQueryPool queryPool);
		//void DestroyQueryPool(MgQueryPool queryPool, MgAllocationCallbacks allocator);
		MgResult GetQueryPoolResults(IMgQueryPool queryPool, UInt32 firstQuery, UInt32 queryCount, IntPtr dataSize, IntPtr pData, UInt64 stride, MgQueryResultFlagBits flags);
		MgResult CreateBuffer(MgBufferCreateInfo pCreateInfo, IMgAllocationCallbacks allocator, out IMgBuffer pBuffer);
		//void DestroyBuffer(MgBuffer buffer, MgAllocationCallbacks allocator);
		MgResult CreateBufferView(MgBufferViewCreateInfo pCreateInfo, IMgAllocationCallbacks allocator, out IMgBufferView pView);
		//void DestroyBufferView(MgBufferView bufferView, MgAllocationCallbacks allocator);
		MgResult CreateImage(MgImageCreateInfo pCreateInfo, IMgAllocationCallbacks allocator, out IMgImage pImage);
		//void DestroyImage(IMgImage image, MgAllocationCallbacks allocator);
		void GetImageSubresourceLayout(IMgImage image, MgImageSubresource pSubresource, out MgSubresourceLayout pLayout);
		MgResult CreateImageView(MgImageViewCreateInfo pCreateInfo, IMgAllocationCallbacks allocator, out IMgImageView pView);
		//void DestroyImageView(MgImageView imageView, MgAllocationCallbacks allocator);
		MgResult CreateShaderModule(MgShaderModuleCreateInfo pCreateInfo, IMgAllocationCallbacks allocator, out IMgShaderModule pShaderModule);
		//void DestroyShaderModule(MgShaderModule shaderModule, MgAllocationCallbacks allocator);
		MgResult CreatePipelineCache(MgPipelineCacheCreateInfo pCreateInfo, IMgAllocationCallbacks allocator, out IMgPipelineCache pPipelineCache);
		//void DestroyPipelineCache(IMgPipelineCache pipelineCache, MgAllocationCallbacks allocator);
		MgResult GetPipelineCacheData(IMgPipelineCache pipelineCache, out byte[] pData);
		MgResult MergePipelineCaches(IMgPipelineCache dstCache, IMgPipelineCache[] pSrcCaches);
		MgResult CreateGraphicsPipelines(IMgPipelineCache pipelineCache, MgGraphicsPipelineCreateInfo[] pCreateInfos, IMgAllocationCallbacks allocator, out IMgPipeline[] pPipelines);
		MgResult CreateComputePipelines(IMgPipelineCache pipelineCache, MgComputePipelineCreateInfo[] pCreateInfos, IMgAllocationCallbacks allocator, out IMgPipeline[] pPipelines);
		//void DestroyPipeline(MgPipeline pipeline, MgAllocationCallbacks allocator);
		MgResult CreatePipelineLayout(MgPipelineLayoutCreateInfo pCreateInfo, IMgAllocationCallbacks allocator, out IMgPipelineLayout pPipelineLayout);
		//void DestroyPipelineLayout(MgPipelineLayout pipelineLayout, MgAllocationCallbacks allocator);
		MgResult CreateSampler(MgSamplerCreateInfo pCreateInfo, IMgAllocationCallbacks allocator, out IMgSampler pSampler);
		//void DestroySampler(MgSampler sampler, MgAllocationCallbacks allocator);
		MgResult CreateDescriptorSetLayout(MgDescriptorSetLayoutCreateInfo pCreateInfo, IMgAllocationCallbacks allocator, out IMgDescriptorSetLayout pSetLayout);
		//void DestroyDescriptorSetLayout(MgDescriptorSetLayout descriptorSetLayout, MgAllocationCallbacks allocator);
		MgResult CreateDescriptorPool(MgDescriptorPoolCreateInfo pCreateInfo, IMgAllocationCallbacks allocator, out IMgDescriptorPool pDescriptorPool);
		//void DestroyDescriptorPool(IMgDescriptorPool descriptorPool, MgAllocationCallbacks allocator);
		//MgResult ResetDescriptorPool(IMgDescriptorPool descriptorPool, UInt32 flags);
		MgResult AllocateDescriptorSets(MgDescriptorSetAllocateInfo pAllocateInfo, out IMgDescriptorSet[] pDescriptorSets);
		MgResult FreeDescriptorSets(IMgDescriptorPool descriptorPool, IMgDescriptorSet[] pDescriptorSets);
		void UpdateDescriptorSets(MgWriteDescriptorSet[] pDescriptorWrites, MgCopyDescriptorSet[] pDescriptorCopies);
		MgResult CreateFramebuffer(MgFramebufferCreateInfo pCreateInfo, IMgAllocationCallbacks allocator, out IMgFramebuffer pFramebuffer);
		//void DestroyFramebuffer(MgFramebuffer framebuffer, MgAllocationCallbacks allocator);
		MgResult CreateRenderPass(MgRenderPassCreateInfo pCreateInfo, IMgAllocationCallbacks allocator, out IMgRenderPass pRenderPass);
//		void DestroyRenderPass(IMgRenderPass renderPass, MgAllocationCallbacks allocator);
		void GetRenderAreaGranularity(IMgRenderPass renderPass, out MgExtent2D pGranularity);
		MgResult CreateCommandPool(MgCommandPoolCreateInfo pCreateInfo, IMgAllocationCallbacks allocator, out IMgCommandPool pCommandPool);
		//void DestroyCommandPool(MgCommandPool commandPool, MgAllocationCallbacks allocator);
		//MgResult ResetCommandPool(MgCommandPool commandPool, MgCommandPoolResetFlagBits flags);
		MgResult AllocateCommandBuffers(MgCommandBufferAllocateInfo pAllocateInfo, IMgCommandBuffer[] pCommandBuffers);
		void FreeCommandBuffers(IMgCommandPool commandPool, IMgCommandBuffer[] pCommandBuffers);
		MgResult CreateSharedSwapchainsKHR(MgSwapchainCreateInfoKHR[] pCreateInfos, IMgAllocationCallbacks allocator, out IMgSwapchainKHR[] pSwapchains);
		MgResult CreateSwapchainKHR(MgSwapchainCreateInfoKHR pCreateInfo, IMgAllocationCallbacks allocator, out IMgSwapchainKHR pSwapchain);
		//void DestroySwapchainKHR(IMgSwapchainKHR swapchain, MgAllocationCallbacks allocator);
		MgResult GetSwapchainImagesKHR(IMgSwapchainKHR swapchain, out IMgImage[] pSwapchainImages);
		MgResult AcquireNextImageKHR(IMgSwapchainKHR swapchain, UInt64 timeout, IMgSemaphore semaphore, IMgFence fence, out UInt32 pImageIndex);

        MgResult CreateObjectTableNVX(MgObjectTableCreateInfoNVX pCreateInfo, IMgAllocationCallbacks allocator, out IMgObjectTableNVX pObjectTable);
        MgResult CreateIndirectCommandsLayoutNVX(MgIndirectCommandsLayoutCreateInfoNVX pCreateInfo, IMgAllocationCallbacks pAllocator, out IMgIndirectCommandsLayoutNVX  pIndirectCommandsLayout);


        MgResult AcquireNextImage2KHR(MgAcquireNextImageInfoKHR pAcquireInfo, ref UInt32 pImageIndex);
        MgResult BindAccelerationStructureMemoryNV(MgBindAccelerationStructureMemoryInfoNV[] pBindInfos);
        MgResult BindBufferMemory2(MgBindBufferMemoryInfo[] pBindInfos);
        MgResult BindImageMemory2(MgBindImageMemoryInfo[] pBindInfos);
        MgResult CompileDeferredNV( UInt64 pipeline, UInt32 shader);
        MgResult CreateAccelerationStructureNV(MgAccelerationStructureCreateInfoNV pCreateInfo, IMgAllocationCallbacks pAllocator, out IMgAcceleratedStructureNV pAccelerationStructure);
        MgResult CreateDescriptorUpdateTemplate(MgDescriptorUpdateTemplateCreateInfo pCreateInfo, IMgAllocationCallbacks pAllocator, ref IMgDescriptorUpdateTemplate pDescriptorUpdateTemplate);
        MgResult CreateRayTracingPipelinesNV(IMgPipelineCache pipelineCache, MgRayTracingPipelineCreateInfoNV[] pCreateInfos, IMgAllocationCallbacks pAllocator, IMgPipeline[] pPipelines);
        MgResult CreateRenderPass2KHR(MgRenderPassCreateInfo2KHR pCreateInfo, IMgAllocationCallbacks pAllocator, out IMgRenderPass pRenderPass);
        MgResult CreateSamplerYcbcrConversion(MgSamplerYcbcrConversionCreateInfo pCreateInfo, IMgAllocationCallbacks pAllocator, IMgSamplerYcbcrConversion pYcbcrConversion);
        MgResult CreateValidationCacheEXT(MgValidationCacheCreateInfoEXT pCreateInfo, IMgAllocationCallbacks pAllocator, IMgValidationCacheEXT pValidationCache);
        MgResult DisplayPowerControlEXT(IMgDisplayKHR display, out MgDisplayPowerInfoEXT pDisplayPowerInfo);
        MgResult GetAccelerationStructureHandleNV(IMgAcceleratedStructureNV accelerationStructure, UIntPtr dataSize, out IntPtr pData);
        MgResult GetCalibratedTimestampsEXT(MgCalibratedTimestampInfoEXT[] pTimestampInfos, out UInt64[] pTimestamps, out UInt64 pMaxDeviation);
        MgResult GetDeviceGroupPresentCapabilitiesKHR(out MgDeviceGroupPresentCapabilitiesKHR pDeviceGroupPresentCapabilities);
        MgResult GetDeviceGroupSurfacePresentModesKHR(IMgSurfaceKHR surface, out MgDeviceGroupPresentModeFlagBitsKHR pModes);
        MgResult GetFenceFdKHR(MgFenceGetFdInfoKHR pGetFdInfo, out int pFd);
        MgResult GetImageDrmFormatModifierPropertiesEXT(IMgImage image, out MgImageDrmFormatModifierPropertiesEXT pProperties);
        MgResult GetMemoryFdKHR( VkMemoryGetFdInfoKHR pGetFdInfo, ref int pFd);
        MgResult GetMemoryFdPropertiesKHR( VkExternalMemoryHandleTypeFlags handleType, int fd, VkMemoryFdPropertiesKHR pMemoryFdProperties);
        MgResult GetMemoryHostPointerPropertiesEXT( VkExternalMemoryHandleTypeFlags handleType, IntPtr pHostPointer, VkMemoryHostPointerPropertiesExt* pMemoryHostPointerProperties);
        MgResult GetRayTracingShaderGroupHandlesNV( UInt64 pipeline, UInt32 firstGroup, UInt32 groupCount, UIntPtr dataSize, IntPtr[] pData);
        MgResult GetSemaphoreFdKHR( VkSemaphoreGetFdInfoKHR pGetFdInfo, ref int pFd);
        MgResult GetShaderInfoAMD( UInt64 pipeline, VkShaderStageFlags shaderStage, VkShaderInfoTypeAMD infoType, ref UIntPtr pInfoSize, IntPtr[] pInfo);
        MgResult GetSwapchainCounterEXT( UInt64 swapchain, VkSurfaceCounterFlagsExt counter, ref UInt64 pCounterValue);
        MgResult GetSwapchainStatusKHR( UInt64 swapchain);
        MgResult GetValidationCacheDataEXT( UInt64 validationCache, ref UIntPtr pDataSize, IntPtr[] pData);
        MgResult ImportFenceFdKHR( [In, Out] VkImportFenceFdInfoKHR pImportFenceFdInfo);
        MgResult ImportSemaphoreFdKHR( [In, Out] VkImportSemaphoreFdInfoKHR pImportSemaphoreFdInfo);
        MgResult MergeValidationCachesEXT( UInt64 dstCache, UInt32 srcCacheCount, UInt64[] pSrcCaches);
        MgResult RegisterDeviceEventEXT( VkDeviceEventInfoExt pDeviceEventInfo, IntPtr pAllocator, UInt64* pFence);
        MgResult RegisterDisplayEventEXT( UInt64 display, VkDisplayEventInfoExt pDisplayEventInfo, IntPtr pAllocator, UInt64* pFence);
        MgResult SetDebugUtilsObjectNameEXT( [In, Out] VkDebugUtilsObjectNameInfoExt pNameInfo);
        MgResult SetDebugUtilsObjectTagEXT( VkDebugUtilsObjectTagInfoExt pTagInfo);
        void DestroyAccelerationStructureNV( UInt64 accelerationStructure, IntPtr pAllocator);
        void DestroyDescriptorUpdateTemplate( UInt64 descriptorUpdateTemplate, IntPtr pAllocator);
        void DestroySamplerYcbcrConversion( UInt64 ycbcrConversion, IntPtr pAllocator);
        void DestroyValidationCacheEXT( UInt64 validationCache, IntPtr pAllocator);
        void GetAccelerationStructureMemoryRequirementsNV( VkAccelerationStructureMemoryRequirementsInfoNV pInfo, VkMemoryRequirements2KHR* pMemoryRequirements);
        void GetBufferMemoryRequirements2( VkBufferMemoryRequirementsInfo2 pInfo, [In, Out] VkMemoryRequirements2 pMemoryRequirements);
        void GetDescriptorSetLayoutSupport( [In, Out] VkDescriptorSetLayoutCreateInfo pCreateInfo, VkDescriptorSetLayoutSupport pSupport);
        void GetDeviceGroupPeerMemoryFeatures( UInt32 heapIndex, UInt32 localDeviceIndex, UInt32 remoteDeviceIndex, ref VkPeerMemoryFeatureFlags pPeerMemoryFeatures);
        void GetDeviceQueue2( [In, Out] VkDeviceQueueInfo2 pQueueInfo, ref IntPtr pQueue);
        void GetImageMemoryRequirements2( VkImageMemoryRequirementsInfo2 pInfo, [In, Out] VkMemoryRequirements2 pMemoryRequirements);
        void GetImageSparseMemoryRequirements2( VkImageSparseMemoryRequirementsInfo2 pInfo, UInt32* pSparseMemoryRequirementCount, VkSparseImageMemoryRequirements2* pSparseMemoryRequirements);
        void SetHdrMetadataEXT( UInt32 swapchainCount, UInt64* pSwapchains, VkHdrMetadataExt* pMetadata);
        void TrimCommandPool( UInt64 commandPool, VkCommandPoolTrimFlags flags);
        void UpdateDescriptorSetWithTemplate( UInt64 descriptorSet, UInt64 descriptorUpdateTemplate, IntPtr pData);

    }
}

